/*
 * shellconf.h
 *
 *  Created on: Nov 11, 2022
 *      Author: rob
 */

#ifndef SHELLCONF_H_
#define SHELLCONF_H_
#define SHELL_CMD_TEST_ENABLED FALSE
#define SHELL_CMD_INFO_ENABLED FALSE
#define SHELL_CMD_SYSTIME_ENABLED FALSE
#define SHELL_CMD_MEM_ENABLED FALSE
#define SHELL_CMD_THREADS_ENABLED FALSE
#define SHELL_USE_HISTORY TRUE
#define SHELL_CMD_EXIT_ENABLED FALSE
#define SHELL_USE_COMPLETION TRUE
#define SHELL_MAX_COMPLETIONS 4
#define SHELL_USE_ESC_SEQ TRUE


#endif /* SHELLCONF_H_ */
